name: CI - Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DTSL/actions/misc/quality-checks@v1
        name: Quality Checks
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
